# Generated by Django 4.2.2 on 2023-06-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tache",
            name="cote",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="tache",
            name="date_extrem",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
