# Generated by Django 4.2.2 on 2023-06-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paramettre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
