# Generated by Django 4.2.2 on 2023-06-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Salle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("salle", models.CharField(blank=True, max_length=100, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(blank=True, max_length=100, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Travee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("travee", models.IntegerField(blank=True, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "salle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cote.salle",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="salle",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cote.site",
            ),
        ),
        migrations.CreateModel(
            name="Rayon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rayon", models.CharField(blank=True, max_length=5, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "travee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cote.travee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Boite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("boite", models.IntegerField(blank=True, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rayon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cote.rayon",
                    ),
                ),
            ],
        ),
    ]
