# Generated by Django 4.2.2 on 2023-06-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serie", models.CharField(blank=True, max_length=5, null=True)),
                ("entite", models.CharField(blank=True, max_length=200, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sous_serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sousserie", models.CharField(blank=True, max_length=5, null=True)),
                ("entite", models.CharField(blank=True, max_length=200, null=True)),
                ("duree", models.IntegerField()),
                ("sort_final", models.CharField(blank=True, max_length=200, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "serie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fond.serie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sous_sous_Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "soussousserie",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                ("entite", models.CharField(blank=True, max_length=200, null=True)),
                ("duree", models.IntegerField()),
                ("sort_final", models.CharField(blank=True, max_length=200, null=True)),
                ("create_at", models.DateField(auto_now_add=True, null=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sousserie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fond.sous_serie",
                    ),
                ),
            ],
        ),
    ]
