# Generated by Django 4.2.2 on 2023-06-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fond", "0002_rename_serie_sous_sous_serie_soussousserie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serie",
            name="entite",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sous_serie",
            name="entite",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="sous_sous_serie",
            name="entite",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
